### PR TITLE
Updates to the Climsoft database and Entity Framework Model

### LINKED ISSUE #18: Unavailability of form_monthly DbSet In The Entity Model
@shadrackkibet  and I just discovered `Property form_monthly() As DbSet(Of form_monthly)` is missing in the entity framework model in class Class `mariadb_climsoft_test_db_v4Entities` . This makes the Entity Framework Context object not to be able to map the to the form_monthly table in the database. For form_monthly to be tested the model needs to be updated. @dannyparsons  @volloholic

### PR DESCRIPTION
**Pull request by isedwards**
Adds required primary keys to `form_monthly`, `observationschedule`, `observationinitial` and `observationfinal` and adds a new table `climsoft_database_metadata` that now contains database version info.

This change will make `form_monthly` and `observationschedule` available.  `observationinitial` and `observationfinal` have also been modified.

This PR completes the code required for #75 and hopefully fixes #18 and #36.

This PR includes `/Climsoft_V4_dbase/climsoft_4.1.1.sql`.  When this file is executed it will DROP (delete) the existing `mariadb_climsoft_db_v4` and `mariadb_climsoft_test_db_v4` databases and recreate them with an empty and inital test data respectively.

### CODE REVIEW

**Comment by isedwards** [comment]
This PR has been replaced by #149

**Comment by mhabimana** [comment]
@isedwards: I was trying to find out this new table"climsoft_database_metadata" in the latest database script attached to the issue #149  but could not get it.

**Comment by isedwards** [comment]
Instead of creating a new table “climsoft_database_metadata” I've now just
used the existing “reg_keys” table to store some new metadata

**Comment by mhabimana** [comment]
@isedwards :Ok,sounds great.

**Pull request closed without merging**
