### PR TITLE
Adding navigation to frmDaily2

### PR DESCRIPTION
**Pull request by maxwellfundi**
This is still in progress. There is bits that needs to be sorted out on how we navigate on the big control.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@Patowhiz I think we can do this for the other forms as a temporary solution. what are your thoughts?

**Comment by Patowhiz** [comment]
Let me test now

**Comment by maxwellfundi** [comment]
Okay, the issue is moving from the big control to the total and then to the save button

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/climsoft-developers Synop and Daily 2 habe new tab order for navigation

**Pull request merged**
