### PR TITLE
HourlyWind

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes partly issue #76
@africanmathsinitiative/developers this is ready for review.
The values that control whether the speed total is required or not are located in the table obselement, elementId 111, column named qcTotalRequired. In that column, 1 means required, 0 means not required. 
@maxwellfundi I'm not quite sure the feedback to give when the total is not entered.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@Patowhiz  do you want to make these changes for the hourly and daily for the total or should i edit those?

**Comment by Patowhiz** [comment]
I can work on the hourly, if the made changes are okay with the team

**Comment by maxwellfundi** [comment]
@mhabimana  @smachua  Whats a sensible feedback to give when the total is not entered? @shadrackkibet  and I will test these changes.

**Comment by mhabimana** [comment]
@maxwellfundi Here is the message the current version is displaying when the total texbox is left blank or has a different value than the calculated total by the computer:
image

**Comment by maxwellfundi** [comment]
@Patowhiz  the issue here is addressed but my concern is for both @smachua form and our form, when you change the values of wind directions and speed on the settings, you need to stop and start the program for them to update properly. Do we need to refresh when the form loads?

**Comment by Patowhiz** [comment]
@maxwellfundi I have written an issue on this in issue #91

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/climsoft-developers I am now going to merge this. We still have the issue raised in #91 Which we will have to relook at

**Pull request merged**
